spring.h2.console.enabled=true
spring.sql.init.platform=h2
spring.datasource.url=jdbc:h2:mem:article
spring.jpa.defer-datasource-initialization=true

server.port=8083
spring.jpa.hibernate.ddl-auto=create-drop
