spring.datasource.url=jdbc:sqlserver://localhost:1433;trustServerCertificate=true;encrypt=true;integratedSecurity=false;databaseName=hardware;
spring.datasource.username=sa
spring.datasource.password=SQL


spring.application.name=Hardware
server.port=8081
logging.level.org.springframework.web=DEBUG
server.error.include-message=always
server.error.include-binding-errors=always